export const SERVICIOS_OT = [
  "Mantenimiento Preventivo",
  "Mantenimiento Correctivo",
  "Mantenimiento Menor",
  "Mantenimiento Medio",
  "Mantenimiento Mayor",
  "Mantenimiento de motores",
  "Instalación Fotovoltaica",
  "Limpieza Robotizada",
  "Servicio Técnico de Drone",
  "Desmantelamiento de paneles solares",
  "Mantenimiento de transformador eléctrico",
  "Falla",
  "Emergencia",
  "Inspección",
] as const;
