/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AprobarTokenRouteImport } from './routes/aprobar.$token'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTrabajosRouteImport } from './routes/_authenticated/trabajos'
import { Route as AuthenticatedTerrenoRouteImport } from './routes/_authenticated/terreno'
import { Route as AuthenticatedSolicitudesRouteImport } from './routes/_authenticated/solicitudes'
import { Route as AuthenticatedRutasRouteImport } from './routes/_authenticated/rutas'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedProgramacionRouteImport } from './routes/_authenticated/programacion'
import { Route as AuthenticatedPlantasRouteImport } from './routes/_authenticated/plantas'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as AuthenticatedMisTrabajosRouteImport } from './routes/_authenticated/mis-trabajos'
import { Route as AuthenticatedMantenimientosRouteImport } from './routes/_authenticated/mantenimientos'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedEquiposRouteImport } from './routes/_authenticated/equipos'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCompletarPerfilRouteImport } from './routes/_authenticated/completar-perfil'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as ApiPublicHooksNotificarProgramacionesRouteImport } from './routes/api/public/hooks/notificar-programaciones'
import { Route as ApiPublicCronRevisarFirmasRouteImport } from './routes/api/public/cron/revisar-firmas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AprobarTokenRoute = AprobarTokenRouteImport.update({
  id: '/aprobar/$token',
  path: '/aprobar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrabajosRoute = AuthenticatedTrabajosRouteImport.update({
  id: '/trabajos',
  path: '/trabajos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTerrenoRoute = AuthenticatedTerrenoRouteImport.update({
  id: '/terreno',
  path: '/terreno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitudesRoute =
  AuthenticatedSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRutasRoute = AuthenticatedRutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramacionRoute =
  AuthenticatedProgramacionRouteImport.update({
    id: '/programacion',
    path: '/programacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantasRoute = AuthenticatedPlantasRouteImport.update({
  id: '/plantas',
  path: '/plantas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisTrabajosRoute =
  AuthenticatedMisTrabajosRouteImport.update({
    id: '/mis-trabajos',
    path: '/mis-trabajos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMantenimientosRoute =
  AuthenticatedMantenimientosRouteImport.update({
    id: '/mantenimientos',
    path: '/mantenimientos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquiposRoute = AuthenticatedEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompletarPerfilRoute =
  AuthenticatedCompletarPerfilRouteImport.update({
    id: '/completar-perfil',
    path: '/completar-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksNotificarProgramacionesRoute =
  ApiPublicHooksNotificarProgramacionesRouteImport.update({
    id: '/api/public/hooks/notificar-programaciones',
    path: '/api/public/hooks/notificar-programaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRevisarFirmasRoute =
  ApiPublicCronRevisarFirmasRouteImport.update({
    id: '/api/public/cron/revisar-firmas',
    path: '/api/public/cron/revisar-firmas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/equipos': typeof AuthenticatedEquiposRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/mantenimientos': typeof AuthenticatedMantenimientosRoute
  '/mis-trabajos': typeof AuthenticatedMisTrabajosRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/plantas': typeof AuthenticatedPlantasRoute
  '/programacion': typeof AuthenticatedProgramacionRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/rutas': typeof AuthenticatedRutasRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/terreno': typeof AuthenticatedTerrenoRoute
  '/trabajos': typeof AuthenticatedTrabajosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aprobar/$token': typeof AprobarTokenRoute
  '/api/public/cron/revisar-firmas': typeof ApiPublicCronRevisarFirmasRoute
  '/api/public/hooks/notificar-programaciones': typeof ApiPublicHooksNotificarProgramacionesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/equipos': typeof AuthenticatedEquiposRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/mantenimientos': typeof AuthenticatedMantenimientosRoute
  '/mis-trabajos': typeof AuthenticatedMisTrabajosRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/plantas': typeof AuthenticatedPlantasRoute
  '/programacion': typeof AuthenticatedProgramacionRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/rutas': typeof AuthenticatedRutasRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/terreno': typeof AuthenticatedTerrenoRoute
  '/trabajos': typeof AuthenticatedTrabajosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aprobar/$token': typeof AprobarTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/cron/revisar-firmas': typeof ApiPublicCronRevisarFirmasRoute
  '/api/public/hooks/notificar-programaciones': typeof ApiPublicHooksNotificarProgramacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/equipos': typeof AuthenticatedEquiposRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/mantenimientos': typeof AuthenticatedMantenimientosRoute
  '/_authenticated/mis-trabajos': typeof AuthenticatedMisTrabajosRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/plantas': typeof AuthenticatedPlantasRoute
  '/_authenticated/programacion': typeof AuthenticatedProgramacionRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/rutas': typeof AuthenticatedRutasRoute
  '/_authenticated/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/_authenticated/terreno': typeof AuthenticatedTerrenoRoute
  '/_authenticated/trabajos': typeof AuthenticatedTrabajosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/aprobar/$token': typeof AprobarTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/cron/revisar-firmas': typeof ApiPublicCronRevisarFirmasRoute
  '/api/public/hooks/notificar-programaciones': typeof ApiPublicHooksNotificarProgramacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auditoria'
    | '/clientes'
    | '/completar-perfil'
    | '/configuracion'
    | '/equipos'
    | '/inventario'
    | '/mantenimientos'
    | '/mis-trabajos'
    | '/notificaciones'
    | '/plantas'
    | '/programacion'
    | '/reportes'
    | '/rutas'
    | '/solicitudes'
    | '/terreno'
    | '/trabajos'
    | '/usuarios'
    | '/aprobar/$token'
    | '/api/public/cron/revisar-firmas'
    | '/api/public/hooks/notificar-programaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auditoria'
    | '/clientes'
    | '/completar-perfil'
    | '/configuracion'
    | '/equipos'
    | '/inventario'
    | '/mantenimientos'
    | '/mis-trabajos'
    | '/notificaciones'
    | '/plantas'
    | '/programacion'
    | '/reportes'
    | '/rutas'
    | '/solicitudes'
    | '/terreno'
    | '/trabajos'
    | '/usuarios'
    | '/aprobar/$token'
    | '/'
    | '/api/public/cron/revisar-firmas'
    | '/api/public/hooks/notificar-programaciones'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auditoria'
    | '/_authenticated/clientes'
    | '/_authenticated/completar-perfil'
    | '/_authenticated/configuracion'
    | '/_authenticated/equipos'
    | '/_authenticated/inventario'
    | '/_authenticated/mantenimientos'
    | '/_authenticated/mis-trabajos'
    | '/_authenticated/notificaciones'
    | '/_authenticated/plantas'
    | '/_authenticated/programacion'
    | '/_authenticated/reportes'
    | '/_authenticated/rutas'
    | '/_authenticated/solicitudes'
    | '/_authenticated/terreno'
    | '/_authenticated/trabajos'
    | '/_authenticated/usuarios'
    | '/aprobar/$token'
    | '/_authenticated/'
    | '/api/public/cron/revisar-firmas'
    | '/api/public/hooks/notificar-programaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AprobarTokenRoute: typeof AprobarTokenRoute
  ApiPublicCronRevisarFirmasRoute: typeof ApiPublicCronRevisarFirmasRoute
  ApiPublicHooksNotificarProgramacionesRoute: typeof ApiPublicHooksNotificarProgramacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/aprobar/$token': {
      id: '/aprobar/$token'
      path: '/aprobar/$token'
      fullPath: '/aprobar/$token'
      preLoaderRoute: typeof AprobarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabajos': {
      id: '/_authenticated/trabajos'
      path: '/trabajos'
      fullPath: '/trabajos'
      preLoaderRoute: typeof AuthenticatedTrabajosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terreno': {
      id: '/_authenticated/terreno'
      path: '/terreno'
      fullPath: '/terreno'
      preLoaderRoute: typeof AuthenticatedTerrenoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes': {
      id: '/_authenticated/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AuthenticatedSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rutas': {
      id: '/_authenticated/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof AuthenticatedRutasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacion': {
      id: '/_authenticated/programacion'
      path: '/programacion'
      fullPath: '/programacion'
      preLoaderRoute: typeof AuthenticatedProgramacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantas': {
      id: '/_authenticated/plantas'
      path: '/plantas'
      fullPath: '/plantas'
      preLoaderRoute: typeof AuthenticatedPlantasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-trabajos': {
      id: '/_authenticated/mis-trabajos'
      path: '/mis-trabajos'
      fullPath: '/mis-trabajos'
      preLoaderRoute: typeof AuthenticatedMisTrabajosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mantenimientos': {
      id: '/_authenticated/mantenimientos'
      path: '/mantenimientos'
      fullPath: '/mantenimientos'
      preLoaderRoute: typeof AuthenticatedMantenimientosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipos': {
      id: '/_authenticated/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof AuthenticatedEquiposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/completar-perfil': {
      id: '/_authenticated/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof AuthenticatedCompletarPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/notificar-programaciones': {
      id: '/api/public/hooks/notificar-programaciones'
      path: '/api/public/hooks/notificar-programaciones'
      fullPath: '/api/public/hooks/notificar-programaciones'
      preLoaderRoute: typeof ApiPublicHooksNotificarProgramacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/revisar-firmas': {
      id: '/api/public/cron/revisar-firmas'
      path: '/api/public/cron/revisar-firmas'
      fullPath: '/api/public/cron/revisar-firmas'
      preLoaderRoute: typeof ApiPublicCronRevisarFirmasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCompletarPerfilRoute: typeof AuthenticatedCompletarPerfilRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedEquiposRoute: typeof AuthenticatedEquiposRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedMantenimientosRoute: typeof AuthenticatedMantenimientosRoute
  AuthenticatedMisTrabajosRoute: typeof AuthenticatedMisTrabajosRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedPlantasRoute: typeof AuthenticatedPlantasRoute
  AuthenticatedProgramacionRoute: typeof AuthenticatedProgramacionRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedRutasRoute: typeof AuthenticatedRutasRoute
  AuthenticatedSolicitudesRoute: typeof AuthenticatedSolicitudesRoute
  AuthenticatedTerrenoRoute: typeof AuthenticatedTerrenoRoute
  AuthenticatedTrabajosRoute: typeof AuthenticatedTrabajosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCompletarPerfilRoute: AuthenticatedCompletarPerfilRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedEquiposRoute: AuthenticatedEquiposRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedMantenimientosRoute: AuthenticatedMantenimientosRoute,
  AuthenticatedMisTrabajosRoute: AuthenticatedMisTrabajosRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedPlantasRoute: AuthenticatedPlantasRoute,
  AuthenticatedProgramacionRoute: AuthenticatedProgramacionRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedRutasRoute: AuthenticatedRutasRoute,
  AuthenticatedSolicitudesRoute: AuthenticatedSolicitudesRoute,
  AuthenticatedTerrenoRoute: AuthenticatedTerrenoRoute,
  AuthenticatedTrabajosRoute: AuthenticatedTrabajosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AprobarTokenRoute: AprobarTokenRoute,
  ApiPublicCronRevisarFirmasRoute: ApiPublicCronRevisarFirmasRoute,
  ApiPublicHooksNotificarProgramacionesRoute:
    ApiPublicHooksNotificarProgramacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
